[package]
name = "tauri-plugin-gcs"
version = "0.1.2"
authors = [ "YourGDPS" ]
description = ""
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-gcs"

[dependencies]
tauri = { version = "2" }
serde = "1.0"
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2.0.2", features = ["build"] }
